FROM maven:3.9.8-eclipse-temurin-22
COPY config/. /opt/app/.
COPY mail-templates/. /opt/app/mail-templates/.
COPY app.jar /opt/app/app.jar
COPY keystore.p12 /opt/app/keystore.p12
COPY vernal-signal-243213-e1053fdc8a6e.json /opt/app/vernal-signal-243213-e1053fdc8a6e.json

ENV SPRING_PROFILES_ACTIVE=production
ENV PROFILE=production

ENV DB_HOST="host.docker.internal"
ENV DB_NAME="team1001iodb"
ENV DB_USERNAME="root"
ENV DB_PASSWORD="pED18ggA!"

ENV cv-wizard-token-name="cvwizard"
ENV cv-wizard-token-value="cvwizard"

ENV GOOGLE_APPLICATION_CREDENTIALS="/opt/app/vernal-signal-243213-e1053fdc8a6e.json"

ENV KAFKA_HOST="10.164.0.14"
ENV KAFKA_PORT="9092"

ENV APP_FILES_SERVICE_HOST="10.164.0.19"
ENV APP_FILES_SERVICE_PORT="8080"

ENV CV_PARSER_HOST="host.docker.internal"
ENV CV_PARSER_PORT="8083"

ENV JOB_TASK_REQUEST_SERVICE_HOST="10.164.0.21"
ENV JOB_TASK_REQUEST_SERVICE_PORT="8080"

ENV INVOICE_ROOT_REQUEST_SERVICE_HOST="10.164.0.21"
ENV INVOICE_ROOT_REQUEST_SERVICE_PORT="8082"

ENV JOB_TASK_SERVICE_HOST="10.164.0.21"
ENV JOB_TASK_SERVICE_PORT="8081"

ENV CV_SERVICE_HOST="10.164.0.20"
ENV CV_SERVICE_PORT="8080"

ENV PDF_GENERATOR_SERVICE_HOST="10.164.0.19"
ENV PDF_GENERATOR_SERVICE_PORT="8082"

ENV MAIL_SENDER_HOST="mailx.ditisklassikaal.nl"

ENV APPLICATION_EVENT_LOGS_HOST="34.34.75.128"
ENV APPLICATION_EVENT_LOGS_PORT="8080"

ENV SERVICE_PROVIDER_CONTRACT_REQUIREMENT_SERVICE_HOST="contracttemplateservice"
ENV SERVICE_PROVIDER_CONTRACT_REQUIREMENT_SERVICE_PORT="8082"

ENV SYSTEM_REQUEST_SERVICE_HOST="system-request-service"
ENV SYSTEM_REQUEST_SERVICE_PORT="8083"

ENV SYSTEM_NOTIFICATION_SERVICE_HOST=systemnotificationservice:8081

WORKDIR /opt/app
EXPOSE 443
EXPOSE 8080
CMD ["java" , "-jar" , "app.jar"]